// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6Uv9BiCXMedwz1mEnmYpiv60nziaPX4',
    appId: '1:166724652406:web:d0e1c86b70d175d94b7e57',
    messagingSenderId: '166724652406',
    projectId: 'authentication-39f91',
    authDomain: 'authentication-39f91.firebaseapp.com',
    storageBucket: 'authentication-39f91.appspot.com',
    measurementId: 'G-0J69CQJ5XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5UAseK9minfJtzkpGCnmHfF-fqKO-4U',
    appId: '1:166724652406:android:f35865e6f0d2603d4b7e57',
    messagingSenderId: '166724652406',
    projectId: 'authentication-39f91',
    storageBucket: 'authentication-39f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vEmVi-HKOBXKii762YASjghPG_U55W8',
    appId: '1:166724652406:ios:14ddde42cf8265984b7e57',
    messagingSenderId: '166724652406',
    projectId: 'authentication-39f91',
    storageBucket: 'authentication-39f91.appspot.com',
    iosClientId: '166724652406-h6l9h56bsemot65nkef2fsnkl2brfp09.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vEmVi-HKOBXKii762YASjghPG_U55W8',
    appId: '1:166724652406:ios:14ddde42cf8265984b7e57',
    messagingSenderId: '166724652406',
    projectId: 'authentication-39f91',
    storageBucket: 'authentication-39f91.appspot.com',
    iosClientId: '166724652406-h6l9h56bsemot65nkef2fsnkl2brfp09.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
